### PR TITLE
use controller_path instead of controller_name to keep namespace

### PR DESCRIPTION
**Pull request by fkoessler**
Hi, I am in the process of refactoring fat_free_crm to turn it into a full Rails engine. This includes namespacing the models.
ransack_ui currently isn't working with namespaced models but it will after this simple merge request is accepted. Thanks for all the good work :+1:

### CODE REVIEW

**Comment by ndbroadbent** [comment]
Cool, looks good to me! Thanks!

**Comment by fkoessler** [comment]
@ndbroadbent  Any chance on releasing ransack_ui version 1.3.2 including this change?

**Comment by steveyken** [comment]
I can cut a release today, if @ndbroadbent hasn't got to it yet. @fkoessler I'm interested in your FFCRM namespacing work... do you have a repo online?

**Comment by fkoessler** [comment]
Thanks @steveyken.
And yes, the fork is on github: https://github.com/fkoessler/fat_free_crm, work in progress. I'm interested in feedback as well!

**Comment by steveyken** [comment]
v1.3.2 is now on rubygems.

**Pull request merged**
