### PR TITLE
Swap to newer ransack API

### LINKED ISSUE #17: DEPRECATION WARNING: #search is deprecated and will be removed in 2.3
See https://github.com/fatfreecrm/fat_free_crm/pull/851

```
DEPRECATION WARNING: #search is deprecated and will be removed in 2.3, please use #ransack instead (called from load_ransack_search at /home/travis/build/fatfreecrm/fat_free_crm/vendor/bundle/ruby/2.4.0/gems/ransack_ui-1.3.4/lib/ransack_ui/controller_helpers.rb:13)
```

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Fix #17

### CODE REVIEW

**Comment by CloCkWeRX** [comment]
@ndbroadbent any chance of this being merged?

**Comment by ndbroadbent** [comment]
Hello, sorry I don't use this library any more, so I don't have much time to maintain it. But I will merge this change!

**Comment by ndbroadbent** [comment]
I've just pushed v1.4.0 with all of your changes.

I see you're also part of the https://github.com/fatfreecrm organization! Maybe I could transfer the project over there? I can also give you access on Rubygems.

**Comment by CloCkWeRX** [comment]
Yup that works re transferring - should add a few extra hands! Thanks

**Comment by CloCkWeRX** [comment]
Re rubygems access, that'd be neat - maybe @steveyken too?

**Comment by ndbroadbent** [comment]
I've just added your email as an owner on rubygems, and steveyken was already an owner as well!

I'm getting this error now: 

```
fatfreecrm/ransack_ui already exists and You don’t have the permission to create public repositories on fatfreecrm
```

Would it be possible to remove the current ransack_ui fork from the org, and add me back as a member? (Haha I think I might have removed myself to stop any notifications since I haven't been involved for a while)

**Comment by steveyken** [comment]
Hey @ndbroadbent ! Sorry, I've just noticed your comment (4 years later... I've renamed fatfreecrm/ransack_ui to fatfreecrm/ransack_ui_ffcrm so the name is free now.

Would you still be up for moving the repo to FFCRM?

cc @CloCkWeRX

**Comment by steveyken** [comment]
I've sent you an invitation to join ffcrm so you can move. If that doesn't work, let me know and I can try

**Comment by ndbroadbent** [comment]
Hi @steveyken! Sure I will move it over now. Hope you are doing well!

**Comment by ndbroadbent** [comment]
It is done!

**Comment by steveyken** [comment]
Thank you!

**Pull request merged**
